apiVersion: apps/v1
kind: Deployment 
metadata:
  name: frontend

spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
    template:
      metadata:
        app: frontend
      spec:
        containers:
          name: frontend
          image: getwellsoon.azurecr.io/samples/python-frontend:latest
          ports:
            containterPort: 80
